# Generated by Django 5.0.7 on 2024-07-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=250)),
                ('subtittle', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=100)),
                ('ISBN', models.CharField(max_length=13)),
            ],
        ),
    ]
